realigning table config for market access
uktrade/data-flow pull request #438
Opened 2020-12-04 11:27 UTC by sekharpanja

### Description of change
Market access pipeline table config need few changes as API response has changed significantly.

Here is the concerning part of the new API response:

```    "economic_assessments": [
      {
        "id": 1,
        "approved": true,
        "archived": false,
        "archived_by": null,
        "archived_on": null,
        "archived_reason": "",
        "automated_analysis_data": null,
        "barrier_id": "123",
        "created_by": {
          "id": 223,
          "name": "Foo bar"
        },
        "created_on": "2019-08-29T08:47:08.487872Z",
        "documents": [
          {
            "id": "123",
            "name": "B-19-ABC (services tax) summary.xlsx",
            "size": 72903,
            "status": "virus_scanned"
          }
        ],
        "economic_impact_assessments": [],
        "explanation": "blah",
        "export_value": 100,
        "import_market_size": 100,
        "modified_on": "2020-11-30T11:47:47.981305Z",
        "modified_by": {
          "id": 223,
          "name": "Foo bar"
        },
        "rating": {
          "code": "HIGH",
          "name": "High"
        },
        "ready_for_approval": true,
        "reviewed_by": {
          "id": 223,
          "name": "Foo bar"
        },
        "reviewed_on": "2019-08-29T08:47:08.487872Z",
        "value_to_economy": null
      }
    ],```

### Checklist

* [ ] Have tests been added to cover any changes?
* [ ] Has the README been updated (if needed)?

2020-12-07 13:13 UTC, abbas123456 requested changes

2020-12-07 13:13 UTC, abbas123456 commented on dataflow/dags/market_access_pipelines.py
> +                            'trade_barrier_id': contexts[0]['id'],
Each economic assessment object already has a field called `barrier_id` so you dont need any transforms here

2020-12-07 13:13 UTC, abbas123456 commented on dataflow/dags/market_access_pipelines.py
> +                                        'trade_barrier_id': contexts[0]['id'],
You need to link each `economic_impact_assessments` object to its corresponding `economic_assessments` object, not the top level trade barrier

2020-12-08 08:43 UTC, abbas123456 commented on dataflow/dags/market_access_pipelines.py
> +                                        'assessment_id': contexts[0]['id'],
Similar to the above comment, the EconomicImpactAssessment object already has a link to its EconomicAssesesment object via a field called `economic_assessment_id`. Therefore you don't need this transform. You need to rename the `assessment_id` field in the field_mapping list to `economic_assessment_id`

2020-12-08 08:44 UTC, abbas123456 commented on dataflow/dags/market_access_pipelines.py
> +                        ('trade_barrier_id', sa.Column('trade_barrier_id', sa.Text)),
This needs to be renamed to `barrier_id` and the related transform needs to be removed as stated above

2020-12-08 11:20 UTC, samuelhwilliams approved these changes

2020-12-08 11:20 UTC, abbas123456 commented on dataflow/dags/market_access_pipelines.py
> +                                        'assessment_id',
This needs to be `economic_assessment_id`

2020-12-08 11:24 UTC, abbas123456 commented on dataflow/dags/market_access_pipelines.py
> +                            ('economic_assessments', 'economic_impact_assessments'),
This shouldn't be a nested tuple, should just be `economic_impact_assessments`

2020-12-08 15:06 UTC, abbas123456 approved these changes

2020-12-08 15:06 UTC, merged